; Change background color
.STACK 64
.DATA
.CODE
MAIN PROC FAR
    MOV AX,@DATA
    MOV DS,AX
    
    MOV AH,00   ;SET MODE OPTION
    MOV AL,03   ;CGA COLOR TEXT MODE OF 80X25
    INT 10H
    
    MOV AH,09    ;DISPLAY OPTION
    MOV BH,00    ;PAGE 0
    MOV AL,20H   ; ASCII FOR SPACE
    MOV CX,800H   ;REPEAT IT 800H
    MOV BL,5FH    ; COLOR
    INT 10H
    
    MOV AH,4CH
    INT 21H
MAIN ENDP
END MAIN